
title: 코드위치 | Code Witch
email: thrif60@gmail.com
description: >-
  개발자를 지망하는 '주니어 개발자' 지망 블로그
baseurl: ""
url: "https://codewitchworld.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

